// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiService.Data;

namespace WebApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220722030740__secondAproach")]
    partial class _secondAproach
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("WebApiService.Model.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalculatorsLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
